Repository nagyesta/lowkey-vault, pull requests merged in 2024-01, with the labels that each got.

#820 Maintenance
  README.md
  build.gradle
  gradle/libs.versions.toml
  gradle/verification-metadata.xml
  lowkey-vault-app/build.gradle
  lowkey-vault-docker/build.gradle
  lowkey-vault-docker/src/test/java/com/github/nagyesta/lowkeyvault/steps/CertificateStepDefAssertion.java
Labels: enhancement

#830 SecretClient doesn't seem to be retrieving managed secrets
  lowkey-vault-app/README.md
  lowkey-vault-app/src/main/java/com/github/nagyesta/lowkeyvault/controller/common/GenericEntityController.java
  lowkey-vault-app/src/main/java/com/github/nagyesta/lowkeyvault/management/VaultImportExportExecutor.java
  lowkey-vault-app/src/main/java/com/github/nagyesta/lowkeyvault/mapper/v7_2/key/KeyEntityToV72KeyItemModelConverter.java
  lowkey-vault-app/src/main/java/com/github/nagyesta/lowkeyvault/mapper/v7_2/secret/SecretEntityToV72SecretItemModelConverter.java
  lowkey-vault-app/src/test/java/com/github/nagyesta/lowkeyvault/controller/v7_2/KeyControllerTest.java
  lowkey-vault-app/src/test/java/com/github/nagyesta/lowkeyvault/controller/v7_2/SecretControllerTest.java
  lowkey-vault-app/src/test/java/com/github/nagyesta/lowkeyvault/controller/v7_3/KeyControllerTest.java
  lowkey-vault-app/src/test/java/com/github/nagyesta/lowkeyvault/controller/v7_3/SecretControllerTest.java
  lowkey-vault-app/src/test/java/com/github/nagyesta/lowkeyvault/controller/v7_4/KeyControllerTest.java
  lowkey-vault-app/src/test/java/com/github/nagyesta/lowkeyvault/controller/v7_4/SecretControllerTest.java
  lowkey-vault-app/src/test/java/com/github/nagyesta/lowkeyvault/service/key/util/Asn1ConverterUtilTest.java
  lowkey-vault-client/README.md
  lowkey-vault-docker/src/test/java/com/github/nagyesta/lowkeyvault/context/CommonTestContext.java
  lowkey-vault-docker/src/test/java/com/github/nagyesta/lowkeyvault/steps/CertificateStepDefAssertion.java
  lowkey-vault-docker/src/test/java/com/github/nagyesta/lowkeyvault/steps/CertificatesStepDefs.java
  lowkey-vault-docker/src/test/java/com/github/nagyesta/lowkeyvault/steps/KeysStepDefs.java
  lowkey-vault-docker/src/test/java/com/github/nagyesta/lowkeyvault/steps/KeysStepDefsAssertions.java
  lowkey-vault-docker/src/test/java/com/github/nagyesta/lowkeyvault/steps/SecretsStepDefs.java
  lowkey-vault-docker/src/test/java/com/github/nagyesta/lowkeyvault/steps/SecretsStepDefsAssertions.java
  lowkey-vault-docker/src/test/resources/com/github/nagyesta/lowkeyvault/certificates/DeleteCertificates.feature
  lowkey-vault-docker/src/test/resources/com/github/nagyesta/lowkeyvault/certificates/ListCertificates.feature
  lowkey-vault-docker/src/test/resources/com/github/nagyesta/lowkeyvault/keys/ListKeys.feature
  lowkey-vault-docker/src/test/resources/com/github/nagyesta/lowkeyvault/secrets/ListSecrets.feature
  lowkey-vault-testcontainers/README.md
Labels: bug

#837 Improve Docker image efficiency
  lowkey-vault-docker/src/docker/Dockerfile
Labels: enhancement, community requested

#838 Triggering a release {patch}
  .release-trigger
Labels: release
